version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'strip-json-comments' # Ignore this package due to this https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
    groups:
      non-major:
        update-types:
          - 'minor'
          - 'patch'
