name: "[CD] Scafflater"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  bump-versions:
    name: "Bump packages version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure CI Git User
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Setup node 15.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Npm Version
        run: |
          npm --version

      - name: Install dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm run Test

      - name: Bumping package versions
        run: |
          npm run version
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
