name: "[CI] Scafflater"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  integration:
    name: "Audit and Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Setup node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Install dependencies
        run: npm ci

      # - name: Run Audit
      #   run: npm audit

      - name: Run Lint
        run: npm run lint

      - name: Run Test
        run: npm run test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
